ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_APP_VERSION
ARG VITE_GIT_COMMIT
ARG VITE_BUILD_DATE
ARG VITE_INTELIMOTOR_BUSINESS_UNIT_ID
ARG VITE_INTELIMOTOR_API_KEY
ARG VITE_INTELIMOTOR_API_SECRET
ARG VITE_AIRTABLE_VALUATION_API_KEY
ARG VITE_AIRTABLE_VALUATION_BASE_ID
ARG VITE_AIRTABLE_VALUATION_TABLE_ID
ARG VITE_AIRTABLE_VALUATION_VIEW
ARG VITE_AIRTABLE_VALUATIONS_STORAGE_TABLE_ID
ARG VITE_AIRTABLE_LEAD_CAPTURE_API_KEY
ARG VITE_AIRTABLE_LEAD_CAPTURE_BASE_ID
ARG VITE_AIRTABLE_LEAD_CAPTURE_TABLE_ID
ARG VITE_IMAGE_CDN_URL
ARG VITE_CLOUDFLARE_R2_PUBLIC_URL

# Stage 1: Build the application
FROM node:18-alpine AS builder

WORKDIR /app

# Copy ONLY package files first for better layer caching
COPY package*.json ./

# Install dependencies (this layer will be cached if package.json doesn't change)
RUN npm ci --prefer-offline --no-audit

# Copy source code AFTER installing dependencies
COPY . .

# Fix symlink: Copy images directory and recreate symlink for public/images
# The symlink in public/ points to ../images, so we need the actual images directory
COPY images/ ./images/

# Re-declare build args in this stage so they're available as ENV vars during build
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_APP_VERSION
ARG VITE_GIT_COMMIT
ARG VITE_BUILD_DATE
ARG VITE_INTELIMOTOR_BUSINESS_UNIT_ID
ARG VITE_INTELIMOTOR_API_KEY
ARG VITE_INTELIMOTOR_API_SECRET
ARG VITE_AIRTABLE_VALUATION_API_KEY
ARG VITE_AIRTABLE_VALUATION_BASE_ID
ARG VITE_AIRTABLE_VALUATION_TABLE_ID
ARG VITE_AIRTABLE_VALUATION_VIEW
ARG VITE_AIRTABLE_VALUATIONS_STORAGE_TABLE_ID
ARG VITE_AIRTABLE_LEAD_CAPTURE_API_KEY
ARG VITE_AIRTABLE_LEAD_CAPTURE_BASE_ID
ARG VITE_AIRTABLE_LEAD_CAPTURE_TABLE_ID
ARG VITE_IMAGE_CDN_URL
ARG VITE_CLOUDFLARE_R2_PUBLIC_URL

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_GIT_COMMIT=$VITE_GIT_COMMIT
ENV VITE_IMAGE_CDN_URL=$VITE_IMAGE_CDN_URL
ENV VITE_CLOUDFLARE_R2_PUBLIC_URL=$VITE_CLOUDFLARE_R2_PUBLIC_URL
ENV VITE_BUILD_DATE=$VITE_BUILD_DATE
ENV VITE_INTELIMOTOR_BUSINESS_UNIT_ID=$VITE_INTELIMOTOR_BUSINESS_UNIT_ID
ENV VITE_INTELIMOTOR_API_KEY=$VITE_INTELIMOTOR_API_KEY
ENV VITE_INTELIMOTOR_API_SECRET=$VITE_INTELIMOTOR_API_SECRET
ENV VITE_AIRTABLE_VALUATION_API_KEY=$VITE_AIRTABLE_VALUATION_API_KEY
ENV VITE_AIRTABLE_VALUATION_BASE_ID=$VITE_AIRTABLE_VALUATION_BASE_ID
ENV VITE_AIRTABLE_VALUATION_TABLE_ID=$VITE_AIRTABLE_VALUATION_TABLE_ID
ENV VITE_AIRTABLE_VALUATION_VIEW=$VITE_AIRTABLE_VALUATION_VIEW
ENV VITE_AIRTABLE_VALUATIONS_STORAGE_TABLE_ID=$VITE_AIRTABLE_VALUATIONS_STORAGE_TABLE_ID
ENV VITE_AIRTABLE_LEAD_CAPTURE_API_KEY=$VITE_AIRTABLE_LEAD_CAPTURE_API_KEY
ENV VITE_AIRTABLE_LEAD_CAPTURE_BASE_ID=$VITE_AIRTABLE_LEAD_CAPTURE_BASE_ID
ENV VITE_AIRTABLE_LEAD_CAPTURE_TABLE_ID=$VITE_AIRTABLE_LEAD_CAPTURE_TABLE_ID

# Build the application
RUN npm run build

# Stage 2: Production server
FROM node:18-alpine

WORKDIR /app

# Copy built assets from builder
COPY --from=builder /app/dist ./dist

# Copy server package files first for better caching
COPY server/package*.json ./

# Install only production dependencies for server
RUN npm ci --only=production --prefer-offline --no-audit

# Copy server code
COPY server/server.js .
COPY server/config.js .

# Add healthcheck
HEALTHCHECK --interval=30s --timeout=3s --start-period=40s --retries=3 \
  CMD node -e "require('http').get('http://localhost:8080/healthz', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"

# Expose port
EXPOSE 8080

# Start server
CMD ["node", "server.js"]
