ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_APP_VERSION
ARG VITE_GIT_COMMIT
ARG VITE_BUILD_DATE
ARG VITE_INTELIMOTOR_BUSINESS_UNIT_ID
ARG VITE_INTELIMOTOR_API_KEY
ARG VITE_INTELIMOTOR_API_SECRET
ARG VITE_AIRTABLE_VALUATION_API_KEY
ARG VITE_AIRTABLE_VALUATION_BASE_ID
ARG VITE_AIRTABLE_VALUATION_TABLE_ID
ARG VITE_AIRTABLE_VALUATION_VIEW
ARG VITE_AIRTABLE_VALUATIONS_STORAGE_TABLE_ID
ARG VITE_AIRTABLE_LEAD_CAPTURE_API_KEY
ARG VITE_AIRTABLE_LEAD_CAPTURE_BASE_ID
ARG VITE_AIRTABLE_LEAD_CAPTURE_TABLE_ID
ARG VITE_IMAGE_CDN_URL
ARG VITE_CLOUDFLARE_R2_PUBLIC_URL

# Stage 1: Build the application
FROM node:18-alpine AS builder

WORKDIR /app

# Copy source code
COPY . .

# Install dependencies
RUN npm install

# Re-declare build args in this stage so they're available as ENV vars during build
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_APP_VERSION
ARG VITE_GIT_COMMIT
ARG VITE_BUILD_DATE
ARG VITE_INTELIMOTOR_BUSINESS_UNIT_ID
ARG VITE_INTELIMOTOR_API_KEY
ARG VITE_INTELIMOTOR_API_SECRET
ARG VITE_AIRTABLE_VALUATION_API_KEY
ARG VITE_AIRTABLE_VALUATION_BASE_ID
ARG VITE_AIRTABLE_VALUATION_TABLE_ID
ARG VITE_AIRTABLE_VALUATION_VIEW
ARG VITE_AIRTABLE_VALUATIONS_STORAGE_TABLE_ID
ARG VITE_AIRTABLE_LEAD_CAPTURE_API_KEY
ARG VITE_AIRTABLE_LEAD_CAPTURE_BASE_ID
ARG VITE_AIRTABLE_LEAD_CAPTURE_TABLE_ID
ARG VITE_IMAGE_CDN_URL
ARG VITE_CLOUDFLARE_R2_PUBLIC_URL

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_GIT_COMMIT=$VITE_GIT_COMMIT
ENV VITE_IMAGE_CDN_URL=$VITE_IMAGE_CDN_URL
ENV VITE_CLOUDFLARE_R2_PUBLIC_URL=$VITE_CLOUDFLARE_R2_PUBLIC_URL
ENV VITE_BUILD_DATE=$VITE_BUILD_DATE
ENV VITE_INTELIMOTOR_BUSINESS_UNIT_ID=$VITE_INTELIMOTOR_BUSINESS_UNIT_ID
ENV VITE_INTELIMOTOR_API_KEY=$VITE_INTELIMOTOR_API_KEY
ENV VITE_INTELIMOTOR_API_SECRET=$VITE_INTELIMOTOR_API_SECRET
ENV VITE_AIRTABLE_VALUATION_API_KEY=$VITE_AIRTABLE_VALUATION_API_KEY
ENV VITE_AIRTABLE_VALUATION_BASE_ID=$VITE_AIRTABLE_VALUATION_BASE_ID
ENV VITE_AIRTABLE_VALUATION_TABLE_ID=$VITE_AIRTABLE_VALUATION_TABLE_ID
ENV VITE_AIRTABLE_VALUATION_VIEW=$VITE_AIRTABLE_VALUATION_VIEW
ENV VITE_AIRTABLE_VALUATIONS_STORAGE_TABLE_ID=$VITE_AIRTABLE_VALUATIONS_STORAGE_TABLE_ID
ENV VITE_AIRTABLE_LEAD_CAPTURE_API_KEY=$VITE_AIRTABLE_LEAD_CAPTURE_API_KEY
ENV VITE_AIRTABLE_LEAD_CAPTURE_BASE_ID=$VITE_AIRTABLE_LEAD_CAPTURE_BASE_ID
ENV VITE_AIRTABLE_LEAD_CAPTURE_TABLE_ID=$VITE_AIRTABLE_LEAD_CAPTURE_TABLE_ID

# Build the application with environment variables
RUN npm run build

# Stage 2: Serve the application from a lightweight server
FROM node:18-alpine

WORKDIR /app

# Copy built assets from the builder stage
COPY --from=builder /app/dist ./dist

# Copy server files
COPY server/server.js .
COPY server/package.json .
COPY server/package-lock.json .
COPY server/config.js .

# Install server dependencies
RUN npm install --production

# Expose the port the server will run on
EXPOSE 8080

# Start the server
CMD ["node", "server.js"]
