name = "trefa-image-proxy"
main = "image-proxy.js"
compatibility_date = "2024-01-01"
account_id = "" # Add your Cloudflare account ID

# Routes - uncomment and update with your domain
# routes = [
#   { pattern = "images.trefa.mx/*", zone_name = "trefa.mx" }
# ]

[observability]
enabled = true
