-- Dynamic Changelog and Roadmap System
-- Allows admins to manage changelog entries and roadmap items via UI
-- Supports AI-assisted features (GitHub commits auto-import, Gemini roadmap suggestions)

-- ============================================
-- CHANGELOG ENTRIES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.changelog_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  version VARCHAR(20) NOT NULL, -- e.g., "1.1.0", "1.2.0"
  release_date DATE NOT NULL,
  category VARCHAR(50) NOT NULL, -- 'fixed', 'added', 'changed', 'technical', 'documentation'
  title TEXT NOT NULL,
  description TEXT,
  items JSONB DEFAULT '[]'::jsonb, -- Array of changelog items with details
  badge_text VARCHAR(100), -- e.g., "Cloudflare Integration", "Bug Fix"
  badge_color VARCHAR(50), -- e.g., "purple", "green", "blue", "red"
  development_hours INTEGER DEFAULT 0,
  files_modified INTEGER DEFAULT 0,
  commit_hash VARCHAR(40), -- GitHub commit hash (if auto-imported)
  imported_from_github BOOLEAN DEFAULT false,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  published BOOLEAN DEFAULT true
);

-- Index for fast version lookups
CREATE INDEX IF NOT EXISTS idx_changelog_version ON public.changelog_entries(version);
CREATE INDEX IF NOT EXISTS idx_changelog_release_date ON public.changelog_entries(release_date DESC);
CREATE INDEX IF NOT EXISTS idx_changelog_category ON public.changelog_entries(category);

-- ============================================
-- ROADMAP ITEMS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.roadmap_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  category VARCHAR(50) NOT NULL, -- 'planned', 'in_progress', 'completed', 'cancelled'
  priority VARCHAR(20) DEFAULT 'medium', -- 'low', 'medium', 'high', 'critical'
  target_quarter VARCHAR(10), -- e.g., "Q1 2025", "Q2 2025"
  target_date DATE,
  estimated_hours INTEGER,
  progress_percentage INTEGER DEFAULT 0 CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
  assignee UUID REFERENCES auth.users(id),
  tags JSONB DEFAULT '[]'::jsonb, -- Array of tags: ["backend", "frontend", "ai", "performance"]
  ai_suggested BOOLEAN DEFAULT false, -- Generated by Gemini AI
  ai_confidence DECIMAL(3,2), -- 0.00 to 1.00 confidence score
  github_issue_number INTEGER, -- Link to GitHub issue
  dependencies JSONB DEFAULT '[]'::jsonb, -- Array of roadmap item IDs this depends on
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  completed_at TIMESTAMPTZ,
  published BOOLEAN DEFAULT true
);

-- Indexes for roadmap
CREATE INDEX IF NOT EXISTS idx_roadmap_category ON public.roadmap_items(category);
CREATE INDEX IF NOT EXISTS idx_roadmap_priority ON public.roadmap_items(priority);
CREATE INDEX IF NOT EXISTS idx_roadmap_target_date ON public.roadmap_items(target_date);
CREATE INDEX IF NOT EXISTS idx_roadmap_progress ON public.roadmap_items(progress_percentage);

-- ============================================
-- GITHUB SYNC LOG TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.github_sync_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sync_type VARCHAR(50) NOT NULL, -- 'commits', 'issues', 'pull_requests'
  commits_processed INTEGER DEFAULT 0,
  entries_created INTEGER DEFAULT 0,
  entries_updated INTEGER DEFAULT 0,
  last_commit_hash VARCHAR(40),
  last_commit_date TIMESTAMPTZ,
  error_message TEXT,
  status VARCHAR(20) DEFAULT 'pending', -- 'pending', 'success', 'failed'
  synced_by UUID REFERENCES auth.users(id),
  synced_at TIMESTAMPTZ DEFAULT now()
);

-- Index for sync log
CREATE INDEX IF NOT EXISTS idx_github_sync_log_date ON public.github_sync_log(synced_at DESC);

-- ============================================
-- AI GENERATION LOG TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.ai_generation_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  generation_type VARCHAR(50) NOT NULL, -- 'roadmap_suggestion', 'changelog_summary', 'commit_analysis'
  ai_model VARCHAR(50), -- 'gemini-pro', 'gemini-1.5-flash', etc.
  prompt TEXT,
  response TEXT,
  tokens_used INTEGER,
  confidence_score DECIMAL(3,2),
  accepted BOOLEAN DEFAULT false, -- Whether admin accepted the AI suggestion
  roadmap_item_id UUID REFERENCES public.roadmap_items(id) ON DELETE CASCADE,
  changelog_entry_id UUID REFERENCES public.changelog_entries(id) ON DELETE CASCADE,
  generated_by UUID REFERENCES auth.users(id),
  generated_at TIMESTAMPTZ DEFAULT now()
);

-- Index for AI log
CREATE INDEX IF NOT EXISTS idx_ai_log_type ON public.ai_generation_log(generation_type);
CREATE INDEX IF NOT EXISTS idx_ai_log_date ON public.ai_generation_log(generated_at DESC);

-- ============================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================

-- Enable RLS
ALTER TABLE public.changelog_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roadmap_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.github_sync_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_generation_log ENABLE ROW LEVEL SECURITY;

-- Changelog Entries Policies
CREATE POLICY "Public can view published changelog entries"
  ON public.changelog_entries FOR SELECT
  USING (published = true);

CREATE POLICY "Admins can manage all changelog entries"
  ON public.changelog_entries FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- Roadmap Items Policies
CREATE POLICY "Public can view published roadmap items"
  ON public.roadmap_items FOR SELECT
  USING (published = true);

CREATE POLICY "Admins can manage all roadmap items"
  ON public.roadmap_items FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- GitHub Sync Log Policies
CREATE POLICY "Only admins can view sync logs"
  ON public.github_sync_log FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

CREATE POLICY "Only admins can create sync logs"
  ON public.github_sync_log FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- AI Generation Log Policies
CREATE POLICY "Only admins can view AI logs"
  ON public.ai_generation_log FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

CREATE POLICY "Only admins can create AI logs"
  ON public.ai_generation_log FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- ============================================
-- FUNCTIONS AND TRIGGERS
-- ============================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER update_changelog_entries_updated_at
  BEFORE UPDATE ON public.changelog_entries
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_roadmap_items_updated_at
  BEFORE UPDATE ON public.roadmap_items
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Function to auto-complete roadmap items when progress reaches 100%
CREATE OR REPLACE FUNCTION auto_complete_roadmap_item()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.progress_percentage = 100 AND OLD.progress_percentage < 100 THEN
    NEW.completed_at = now();
    NEW.category = 'completed';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER auto_complete_roadmap
  BEFORE UPDATE ON public.roadmap_items
  FOR EACH ROW
  EXECUTE FUNCTION auto_complete_roadmap_item();

-- ============================================
-- SEED DATA (Example v1.1.0 entry)
-- ============================================
INSERT INTO public.changelog_entries (version, release_date, category, title, description, items, badge_text, badge_color, development_hours, published)
VALUES
(
  '1.1.0',
  '2025-11-08',
  'fixed',
  'Critical Bug Fixes',
  'Fixed several critical bugs affecting user experience and tracking',
  '[
    {"icon": "🐛", "title": "Redirect bug causing authenticated users to be redirected on every page load", "details": "Fixed AuthHandler.tsx to only redirect when loginRedirect exists in localStorage"},
    {"icon": "🎥", "title": "Video player on Financiamientos landing page not visible", "details": "Refactored to use same iframe embed code as homepage, replacing youtube-nocookie.com with standard youtube.com/embed"},
    {"icon": "📧", "title": "Email notification logs API key error", "details": "Added session verification before querying email_notification_logs, improved error handling for RLS policy issues"},
    {"icon": "✏️", "title": "Hero heading typography on Financiamientos page", "details": "Reduced letter-spacing and added WebkitTextStroke for enhanced boldness"}
  ]'::jsonb,
  'Bug Fixes',
  'red',
  8,
  true
),
(
  '1.1.0',
  '2025-11-08',
  'added',
  'Cloudflare Google Tag Gateway Support',
  'Enhanced marketing tracking with first-party data collection',
  '[
    {"icon": "🚀", "title": "gtm_server_container_url field to MarketingConfig interface", "details": "Optional server-side GTM container URL support"},
    {"icon": "🔧", "title": "use_cloudflare_tag_gateway flag", "details": "Enable/disable Cloudflare first-party tracking"},
    {"icon": "🤖", "title": "Automatic Tag Gateway detection with console logging", "details": "Detects when Tag Gateway is active and logs for debugging"},
    {"icon": "📊", "title": "Server container URL support via dataLayer", "details": "Passes server container URL to GTM for enhanced tracking"},
    {"icon": "📈", "title": "Expected 11% average uplift in data signals", "details": "Per Cloudflare - first-party tracking bypasses ad blockers"}
  ]'::jsonb,
  'New Feature',
  'purple',
  6,
  true
);

COMMENT ON TABLE public.changelog_entries IS 'Stores changelog entries that can be managed by admins via UI';
COMMENT ON TABLE public.roadmap_items IS 'Stores roadmap items with AI-assisted suggestions from Gemini';
COMMENT ON TABLE public.github_sync_log IS 'Tracks GitHub commit sync operations for automatic changelog generation';
COMMENT ON TABLE public.ai_generation_log IS 'Logs all AI-generated suggestions and their acceptance status';
